github:
  description: "Portal Interface for Apache Airavata Custos Security"
  homepage: https://airavata.apache.org/
  labels:
    - airavata
    - apache
    - security
    - oauth2
    - openidconnect
    - authentication
    - authorization

  features:
    wiki: true
    issues: true
    projects: true
