version: "3.3"
services:
  web:
    image: "apachecustos/emc-portal:latest"
    ports:
      - "8080:8080"
    volumes:
      - /Users/isururanawaka/Documents/Airavata_Repository/airavata-custos-portal/custos-demo-gateway/privkey.pem:/etc/nginx/privkey.pem
      - /Users/isururanawaka/Documents/Airavata_Repository/airavata-custos-portal/custos-demo-gateway/fullchain.pem:/etc/nginx/fullchain.pem
    environment:
      VUE_APP_CLIENT_ID: ''
      VUE_APP_CLIENT_SEC: ''
      VUE_APP_REDIRECT_URI: 'http://localhost:8080/callback'
      VUE_APP_DATA_LAKE_DRMS_URL: 'http://149.165.157.235:10000/v1.0/api'

